mikehub/config/routes.rb
Rails.application.routes.draw do

  get 'sessions/login' => 'sessions#login'

  post 'sessions/create' => 'sessions#create'

  get 'sessions/logout' => 'sessions#logout'

  root "pages#index"

  get 'users/new' => 'users#new'

  post 'users/create' => 'users#create'

  delete 'users/:id' => 'users#destroy', as: "user_delete"

  get 'users/:id' => 'users#show', as: "user"

  get 'articles/new'

  post 'articles' => 'articles#create', as: "articles"

  get 'articles/:id' => 'articles#show', as: "article"

  get 'articles/:id/edit' => 'articles#edit', as: "edit_article"

  patch 'articles/:article_id/edits/:id' => 'articles#update', as: "update_article"

  delete 'articles/:id' => 'articles#destroy', as: 'article_delete'

  post "search" => "pages#search"

  get "articles/:article_id/edits/new" => "edits#new", as: "new_edit"
  post "articles/:article_id/edits" => "edits#create", as: "article_edits"

  get "articles/:article_id/edits" => "edits#index", as: "view_all_edits"

  get "edits/:id" => "edits#show", as: "edit"

  namespace :admin do
    patch "users/:user_id" => "users#make_admin"
    resources :users, :articles
  end

end

mikehub/app/models/edit.rb
class Edit < ActiveRecord::Base
  belongs_to :article
  belongs_to :editor, class_name: "User"

end

mikehub/app/controllers/edits_controller.rb
class EditsController < ApplicationController
  def index
    @article = Article.find(params[:article_id])
    @edits = @article.edits.order(:created_at => :desc)
  end

  def new
    @article = Article.find(params[:article_id])
    @edit = Edit.new(title: @article.title, subtitle: @article.subtitle, content: @article.content)
  end

  def create
    @article = Article.find(params[:article_id])
    @edit = Edit.create(edit_params)
    current_user.edits << @edit
    @article.edits << @edit
    redirect_to @edit
  end

  def show
    @edit = Edit.find(params[:id])
    @article = Article.find(@edit.article.id)
  end

  private
    def edit_params
      params.require(:edit).permit(:title, :subtitle, :content)
    end
end

mikehub/app/views/edits/index.html.erb
<div class="edits-index">
  <h3>Suggested edits for <%= link_to @article.title, article_path(@article) %></h3>
  <% @edits.each do |edit| %>
    <p>
      <span class="link-to-edit">
        <%= link_to(edit) do %>
          <%= edit.created_at.strftime('%B %e, %Y') %>
        <% end %>
      </span>
      <br>
      <span class="article-byline edit-byline">Edit suggested by <%= edit.editor.full_name %></span>
    </p>
  <% end %>
</div>

mikehub/app/views/edits/new.html.erb
<div style="width: 900px; margin:auto;">
<%= form_for [@article, @edit], method: :post do |f| %>
  <p><%= label_tag "Article title" %>:
  <%= f.text_field :title %>
  <%= label_tag "Article Subtitle" %>:
  <%= f.text_field :subtitle %></p>
<textarea name="edit[content]" >
  <%= @edit.content %>

</textarea>
<%= submit_tag "Submit", id: "article-submit" %>
<% end %>


<script>
    CKEDITOR.replace( 'edit[content]' );
</script>
<div>

mikehub/app/views/edits/show.html.erb
<div class="article_show">
  <p class="edit-note">
    Note: This file is a suggested edit to an existing article.
    <br>
    <% if current_user.articles.include?(@article) || current_user.admin %>
      <% if @edit.accepted %>
        Status: Accepted on <%= @edit.updated_at.strftime('%B %e, %Y') %>
      <% else %>
        <%= link_to "Click here", update_article_path(@article, @edit), method: :patch %> to accept this edit. (This will update the article to incorporate the changes below.)
      <% end %>
    <% else %>
      If you are the author of the original article, you can log in to review and accept this edit.
    <% end %>
  </p>

  <h3><%= @edit.title %></h3>
  <h2><%= @edit.subtitle %></h2>
  <span class="article-byline">
    Edit suggested by <%= link_to @edit.editor.full_name, user_path(@edit.editor) %>.
    Original article can be found <%= link_to "here", @article %>
  </span>
  <br>
  <span class="article-byline">
    This edit
    <% if @edit.accepted %>
      has
    <% else %>
      has not yet
    <% end %>
    been accepted by the article's author.
  </span>
  <p><%= @edit.content.html_safe %></p>

</div>