mikehub/config/routes.rb
Rails.application.routes.draw do

  get 'sessions/login' => 'sessions#login'

  post 'sessions/create' => 'sessions#create'

  get 'sessions/logout' => 'sessions#logout'

  root "pages#index"

  get 'users/new' => 'users#new'

  post 'users/create' => 'users#create'

  delete 'users/:id' => 'users#destroy', as: "user_delete"

  get 'users/:id' => 'users#show', as: "user"

  get 'articles/new'

  post 'articles' => 'articles#create', as: "articles"

  get 'articles/:id' => 'articles#show', as: "article"

  get 'articles/:id/edit' => 'articles#edit', as: "edit_article"

  patch 'articles/:article_id/edits/:id' => 'articles#update', as: "update_article"

  delete 'articles/:id' => 'articles#destroy', as: 'article_delete'

  post "search" => "pages#search"

  get "articles/:article_id/edits/new" => "edits#new", as: "new_edit"
  post "articles/:article_id/edits" => "edits#create", as: "article_edits"

  get "articles/:article_id/edits" => "edits#index", as: "view_all_edits"

  get "edits/:id" => "edits#show", as: "edit"

  namespace :admin do
    patch "users/:user_id" => "users#make_admin"
    resources :users, :articles
  end

end

mikehub/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MikeHub</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <script src="//cdn.ckeditor.com/4.5.5/standard/ckeditor.js"></script>
</head>
<body>
  <header>
    <p class="header-links">
     <% if admin_logged_in? %>
        Hello, <%=  current_user.first_name %>! <%= link_to "Admin", admin_user_path(current_user) %> | <%= link_to "Log out", sessions_logout_path %>
      <% elsif logged_in? %>
        Hello, <%= current_user.first_name %>! <%= link_to "Log out", sessions_logout_path %> | <%= link_to "Create a new article", articles_new_path %>
      <% else %>
        Hello, guest! <%= link_to "Log in", sessions_login_path %> or <%= link_to "Register", users_new_path %>
      <% end %>
      | <%= link_to "Home", root_path %>
    </p>
    <%= form_tag "/search", class: "searchbar", method: :post do %>
      <input type="text" name="search_term">
      <input type="submit" value="Search">
    <% end %>
    <h1 class="header-title">MikeHub</h1>
    <hr>
  </header>
<%= yield %>

  <hr>

  <footer>
  </footer>

</body>
</html>