mikehub/config/routes.rb
Rails.application.routes.draw do

  get 'sessions/login' => 'sessions#login'

  post 'sessions/create' => 'sessions#create'

  get 'sessions/logout' => 'sessions#logout'

  root "pages#index"

  get 'users/new' => 'users#new'

  post 'users/create' => 'users#create'

  delete 'users/:id' => 'users#destroy', as: "user_delete"

  get 'users/:id' => 'users#show', as: "user"

  get 'articles/new'

  post 'articles' => 'articles#create', as: "articles"

  get 'articles/:id' => 'articles#show', as: "article"

  get 'articles/:id/edit' => 'articles#edit', as: "edit_article"

  patch 'articles/:article_id/edits/:id' => 'articles#update', as: "update_article"

  delete 'articles/:id' => 'articles#destroy', as: 'article_delete'

  post "search" => "pages#search"

  get "articles/:article_id/edits/new" => "edits#new", as: "new_edit"
  post "articles/:article_id/edits" => "edits#create", as: "article_edits"

  get "articles/:article_id/edits" => "edits#index", as: "view_all_edits"

  get "edits/:id" => "edits#show", as: "edit"

  namespace :admin do
    patch "users/:user_id" => "users#make_admin"
    resources :users, :articles
  end

end

mikehub/app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :author, class_name: "User"
  has_many :edits
  has_many :editors, through: :edits, source: :editor

  validates :title, presence: true

  def has_edits?
    self.edits.count > 0
  end

end

mikehub/app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_filter :authorized?


  private

  def authorized?
    unless admin_logged_in?
      flash[:error] = "You are not authorized to view that page."
      redirect_to root_path
    end
  end


end

mikehub/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :show]

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.valid?
      @article.save
      redirect_to @article
    else
      @errors = @article.errors.full_messages
      render 'new'
    end
  end

  def show
    @edits = @article.edits
  end

  def edit
  end

  def update
    @article = Article.find(params[:article_id])
    @edit = Edit.find(params[:id])
    @article.update_attributes(title: @edit.title, subtitle: @edit.subtitle, content: @edit.content)
    @edit.update_attribute(:accepted, true)
    redirect_to @article
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :subtitle, :content)
  end

end

mikehub/app/helpers/articles_helper.rb
module ArticlesHelper
  def make_html(string)
    string.html_safe
  end

  def clean_string_from_html(string)
    string = ActionView::Base.full_sanitizer.sanitize(string)
    string = string.gsub(/(&#13;)/, "")
    string = string.gsub(/(&quot;)/, "")
  end

  def recent_articles(string)
    string = clean_string_from_html(string)
    string[0..60]
  end

  def feature_articles(string)
    string = clean_string_from_html(string)
    string[0..150]
  end

  def find_subheading(article)
    heading_matcher = /((\r\n){2}<p>)([\w ]*\w[\w ])(<\/p>(\r\n){2})/
    link = '\3'
    p link
    link_open_tag = '<a name="\3" href="/articles/' + article.id.to_s + '/#\3">'
    link_close_tag = '</a>'
    replacement_text = '\1' + link_open_tag +'\3' + link_close_tag + '\4'
    article.content.gsub(heading_matcher, replacement_text)
  end
end

mikehub/app/views/articles/edit.html.erb
<div class="article_create_edit">
  <%= form_for @article do |f| %>
    <%= label_tag :article, "Title" %>
    <%= text_field(:article, :title, size: "80%")%>
    <%= label_tag :article, "Subtitle" %>
    <%= text_field(:article,:subtitle, size: "70%")  %>
    <%= label_tag :article, "Content" %>
    <%= text_area(:article, :content, size: "95%x30%")%>
    <%= submit_tag "Submit" %>
  <% end %>
</div>

mikehub/app/views/articles/new.html.erb
<div style="width: 900px; margin:auto;">
<%= form_for @article do |f| %>
  <p><%= label_tag "Article title" %>:
  <%= f.text_field :title %>
  <%= label_tag "Article Subtitle" %>:
  <%= f.text_field :subtitle %></p>
<textarea name="article[content]" >


</textarea>
<%= submit_tag "Submit", id: "article-submit" %>
<% end %>


<script>
    CKEDITOR.replace( 'article[content]' );
</script>
<div>

mikehub/app/views/articles/show.html.erb
<div class="article_show">
  <% if logged_in? %>
    <% if current_user.articles.include?(@article) || current_user.admin %>
      <%= link_to 'Edit this article', new_edit_path(@article) %>
       | <%= link_to 'Delete this article', article_delete_path(@article), method: :delete %>
       | <%= link_to 'View suggested edits', view_all_edits_path(@article) %>
    <% else %>
      <%= link_to 'Suggest an edit to this article', new_edit_path(@article) %>
    <% end %>
  <% end %>


  <h3><%= @article.title %></h3>
  <h2><%= @article.subtitle %></h2>
  <p><%= find_subheading(@article).html_safe %></p>
</div>


  <span class="article-byline">Written by <%= link_to @article.author.full_name, user_path(@article.author) %></span>
  <br>
  <% if @article.has_edits? %>
    <span class="article-byline">
      Contributors:
      <% @edits.each do |edit| %>
          <span>
            <% if edit.accepted %>
              <%= link_to(edit.editor) do %>
                <%= edit.editor.full_name %>
              <% end %>
            <% end %>
          </span>
      <% end %>
    </span>
  <% end %>
  <p><%= make_html(@article.content)%></p>
</div>