mikehub/config/routes.rb
Rails.application.routes.draw do

  get 'sessions/login' => 'sessions#login'

  post 'sessions/create' => 'sessions#create'

  get 'sessions/logout' => 'sessions#logout'

  root "pages#index"

  get 'users/new' => 'users#new'

  post 'users/create' => 'users#create'

  delete 'users/:id' => 'users#destroy', as: "user_delete"

  get 'users/:id' => 'users#show', as: "user"

  get 'articles/new'

  post 'articles' => 'articles#create', as: "articles"

  get 'articles/:id' => 'articles#show', as: "article"

  get 'articles/:id/edit' => 'articles#edit', as: "edit_article"

  patch 'articles/:article_id/edits/:id' => 'articles#update', as: "update_article"

  delete 'articles/:id' => 'articles#destroy', as: 'article_delete'

  post "search" => "pages#search"

  get "articles/:article_id/edits/new" => "edits#new", as: "new_edit"
  post "articles/:article_id/edits" => "edits#create", as: "article_edits"

  get "articles/:article_id/edits" => "edits#index", as: "view_all_edits"

  get "edits/:id" => "edits#show", as: "edit"

  namespace :admin do
    patch "users/:user_id" => "users#make_admin"
    resources :users, :articles
  end

end

mikehub/app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, foreign_key: :author_id
  has_many :edits, foreign_key: :editor_id
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_format_of :email, :with => /\A[\w+\-.]+@(dbc|DBC|Dbc|dBc|dbC).com\Z/

  has_secure_password

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

end

mikehub/app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authorized?

  def show
    @user = User.find_by(id: params[:id])
  end

  def index
    @all_users = User.all
  end

  def delete
    @target_user = User.find_by(id: user_id)
    @target_user.destroy
  end

  def make_admin
    @user = User.find_by(id: params[:user_id])
    p @user
    @user.admin = true
    @user.save
    redirect_to admin_user_path(current_user)
  end

  private

  def authorized?
    unless admin_logged_in?
      flash[:error] = "You are not authorized to view that page."
      redirect_to root_path
    end
  end


end

mikehub/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to "/"
    else
      render "new"
    end
  end


  def show
    @user = User.find_by(id: params[:id])
    @articles = @user.articles
  end


  def destroy
    if admin_logged_in?
      @user = User.find_by(id: params[:id])
      @user.destroy
      redirect_to root_path
    else
      flash[:error] = "You are not authorized to view that page."
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :img_url, :password)
  end
end

mikehub/app/helpers/users_helper.rb
module UsersHelper
end

mikehub/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

mikehub/app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

mikehub/app/views/users/new.html.erb
<h2>Sign Up</h2>
<div class="user-form-div">
  <%= form_for @user, :url => users_create_path do |f| %>
    <p><%= f.label :first_name %>:
    <%= f.text_field :first_name %></p>
    <p><%= f.label :last_name %>:&nbsp;
    <%= f.text_field :last_name %></p>
    <p><%= f.label :email %>:&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
    <%= f.text_field :email %></p>
    <p><%= f.label :password %>:&nbsp; &nbsp;
    <%= f.text_field :password %></p>
    <p><%= f.submit "Register" %></p>
  <% end %>
</div>

mikehub/app/views/users/show.html.erb
<div class="user_show">

<h3> <%= @user.first_name %> <%= @user.last_name %> </h3>
  <ul>
    <li> <%= @user.email %> </li>
    <li id ="profile_page_photo"> <%= image_tag(@user.img_url) %> </li>
    <% @articles.each do |article| %>
        <li class="article"> <a href="/articles/<%= article.id %>"> <%= article.title %> </a> </li>
     <% end %>
  </ul>
</div>

<% if admin_logged_in? %>
  <p> Delete this user by clicking <%= link_to "delete", user_delete_path(@user), method: :delete, data:{confirm: 'Are you sure you want to delete this user?'} %> <p>

    <% if @user.admin != true %>
      <p> Make this user an admin by clicking <%= link_to "here", admin_path(@user.id), method: :patch, data:{confirm: 'Are you sure you want to make this user an admin?'} %> </p>
    <% end %>
<% end %>